workflows:
  ios-release:
    name: iOS Build & Upload
    
    environment:
      flutter: 3.29.3
      xcode: latest
      vars:
        APP_STORE_CONNECT_TEAM_ID: "7H72D96Y7C"
        BUNDLE_ID: "com.kennatech.txng"
      groups:
        - admin

    scripts:
      - name: Install dependencies
        script: flutter pub get
        
      - name: Set iOS deployment target
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, "15.5"/' ios/Podfile

      - name: Install pods
        script: |
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Build iOS (xcodebuild)
        script: |
          cd ios

          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive \
            archive \
            DEVELOPMENT_TEAM=$APP_STORE_CONNECT_TEAM_ID \
            PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID \
            -allowProvisioningUpdates

          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist /dev/stdin \
            -exportPath build <<EOF
          {
            "method": "app-store",
            "teamID": "$APP_STORE_CONNECT_TEAM_ID",
            "signingStyle": "automatic"
          }
          EOF

          cd ..

    
    publishing:
      app_store_connect:
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: false